#!/bin/bash

for var in 1 2 3 4 5
do
    fio --filename=/dev/nvme0n1 --name=fio_bb_test --direct=1 --rw=write --size=4K --offset=0 --bs=4K --numjobs=1 --group_reporting=1 --time_based=1 --runtime=300 --offset_increment=1M;
    echo 3 > /proc/sys/vm/drop_caches;
    sleep 3;
done
echo "\n"
for var in 1 2 3 4 5
do
    taskset -c 0-1 fio --filename=/dev/nvme0n1 --name=fio_bb_test --direct=1 --rw=write --size=4K --offset=0 --bs=4K --numjobs=2 --group_reporting=1 --time_based=1 --runtime=300 --offset_increment=1M;
    echo 3 > /proc/sys/vm/drop_caches;
    sleep 3;
done
echo "\n"
for var in 1 2 3 4 5
do
    taskset -c 0-3 fio --filename=/dev/nvme0n1 --name=fio_bb_test --direct=1 --rw=write --size=4K --offset=0 --bs=4K --numjobs=4 --group_reporting=1 --time_based=1 --runtime=300 --offset_increment=1M;
    echo 3 > /proc/sys/vm/drop_caches;
    sleep 3;
done
echo "\n"
for var in 1 2 3 4 5
do
    taskset -c 0-7 fio --filename=/dev/nvme0n1 --name=fio_bb_test --direct=1 --rw=write --size=4K --offset=0 --bs=4K --numjobs=8 --group_reporting=1 --time_based=1 --runtime=300 --offset_increment=1M;
    echo 3 > /proc/sys/vm/drop_caches;
    sleep 3;
done
echo "\n"
for var in 1 2 3 4 5
do
    taskset -c 0-15 fio --filename=/dev/nvme0n1 --name=fio_bb_test --direct=1 --rw=write --size=4K --offset=0 --bs=4K --numjobs=16 --group_reporting=1 --time_based=1 --runtime=300 --offset_increment=1M;
    echo 3 > /proc/sys/vm/drop_caches;
    sleep 3;
done
echo "\n"
for var in 1 2 3 4 5
do
    taskset -c 0-31 fio --filename=/dev/nvme0n1 --name=fio_bb_test --direct=1 --rw=write --size=4K --offset=0 --bs=4K --numjobs=32 --group_reporting=1 --time_based=1 --runtime=300 --offset_increment=1M;
    echo 3 > /proc/sys/vm/drop_caches;
    sleep 3;
done